apiVersion: batch/v1
kind: Job
metadata:
  name: s3-uploader-job
  namespace: default
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: aws-cli
        image: amazon/aws-cli:latest
        env:
        - name: AWS_ACCESS_KEY_ID
          value: "test"
        - name: AWS_SECRET_ACCESS_KEY
          value: "test"
        - name: AWS_DEFAULT_REGION
          value: "us-east-1"
        - name: AWS_REQUEST_CHECKSUM_CALCULATION
          value: "WHEN_REQUIRED"
        - name: AWS_RESPONSE_CHECKSUM_VALIDATION
          value: "WHEN_REQUIRED"
        command: ["/bin/sh", "-c"]
        args:
        - |
          set -e
          echo "--- Creando reporte interno en el Pod ---"
          echo "Reporte de telemetria generado a las $(date)" > /tmp/reporte.txt

          echo "--- Verificando/Creando Bucket S3 en LocalStack ---"
          aws --endpoint-url=http://localstack-service:4566 s3 mb s3://reportes-cluster || true

          echo "--- Subiendo archivo a S3 via s3api (sin trailers) ---"
          aws --endpoint-url=http://localstack-service:4566 s3api put-object \
            --bucket reportes-cluster \
            --key "reporte-$(date +%s).txt" \
            --body /tmp/reporte.txt

          echo "--- Proceso completado con exito ---"